version: 2

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/src/*"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Sofia"

    commit-message:
      prefix: "fix: "

    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"