---
variables:
  PROJECT_DIR: One.Settix.RabbitMQ

trigger:
  branches:
    include: [master,beta,preview]
  paths:
    exclude: [CHANGELOG.md]

pool:
  vmImage: ubuntu-22.04

stages:

- stage : DeployStage
  displayName: 'Deploy stage'
  jobs:
  - job: build_pack_publish

    steps:
    - checkout: self
      clean: true
      persistCredentials: true

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x'
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      name: build
      inputs:
        command: build
        projects: 'src/$(PROJECT_DIR)/*.csproj'

    - task: Bash@3
      name: release
      displayName: semantic release + pack
      env:
        STAGING_PATH: $(Build.StagingDirectory)
      inputs:
        targetType: 'inline'
        script: |
          npm install -g semantic-release@22.0.12 @semantic-release/exec@latest @semantic-release/changelog@latest @semantic-release/git@latest
          time npx semantic-release --no-ci
          time npx semantic-release --no-ci
          # few commands for debugging purposes
          ls -l $STAGING_PATH/*.nupkg
          echo dotnet msbuild `dotnet msbuild --version`
          echo dotnet nuget `dotnet nuget --version`
          echo dotnet `dotnet --version`

    - task: NuGetCommand@2
      name: publish
      enabled: true
      condition: and(eq(variables['newVer'], 'yes'), succeeded())
      inputs:
        command: 'push'
        packagesToPush: '$(Build.StagingDirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'CI-AzurePipelines'
